#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # Need number and special char
    args.password = "1Strong-Password"

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.2c5089d1.name = "Last Packaging v1 version"
