#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # Need number and special char
    args.password = "1Strong-Password"

    # ------------
    # Tests to run
    # ------------

    #test_upgrade_from.2c5089d1.name = "Last Packaging v1 version"
    test_upgrade_from.849ce4abcd11f36217c0a9e1ef50498e9cd9a4a1.name = "Upgrade from 6.3.36~ynh1"
