#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-app" >/dev/null; then
    yunohost service remove "$app-app"
fi
if ynh_hide_warnings yunohost service status "$app-worker" >/dev/null; then
    yunohost service remove "$app-worker"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd"$app-app"
ynh_config_remove_systemd"$app-worker"

# Remove the dedicated NGINX config
ynh_config_remove_nginx

ynh_ruby_remove

ynh_nodejs_remove

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
