#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_install_ruby__2
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "$app-app" >/dev/null; then
    yunohost service remove "$app-app"
fi
if ynh_exec_warn_less yunohost service status "$app-worker" >/dev/null; then
    yunohost service remove "$app-worker"
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config --service="$app-app"
ynh_remove_systemd_config --service="$app-worker"

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing Ruby..." --weight=1
ynh_remove_ruby

ynh_script_progression --message="Removing NodeJS..." --weight=1
ynh_remove_nodejs

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
