#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app-app" >/dev/null; then
    yunohost service remove "$app-app"
fi
if ynh_hide_warnings yunohost service status "$app-worker" >/dev/null; then
    yunohost service remove "$app-worker"
fi

ynh_config_remove_systemd "$app-app"
ynh_config_remove_systemd "$app-worker"

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
